apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-prtg-exporter.fullname" . }}
  labels:
    {{- include "prometheus-prtg-exporter.labels" . | nindent 4 }}
data:
  application.yml: {{ toYaml .Values.config | indent 2 }}
